from enum import Enum


class EventType(Enum):
    START = 1
    EXIT = 2
    SAVE_GAME_PARAMETERS = 3
    CLICK_DISPLAYED_CARD = 4
    CLICK_DECK_CARD = 5
    CLICK_TAKE_TOKEN_GAMEBOARD = 6
    CLICK_GIVE_BACK_PLAYER_TOKEN = 7
    CLICK_TILE = 8
    POPUP_PURCHASE = 9
    POPUP_RESERVE = 10
    CANCEL_ACTION = 11
    VALIDATE_ACTION = 12
    RESERVE_PURCHASE = 13
    CLOSE_POPUP = 14
